DROP TABLE IF EXISTS xzero;
DROP TABLE IF EXISTS sequence;
DROP TABLE IF EXISTS prime;

CREATE TABLE xzero (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  formula TEXT UNIQUE NOT NULL
);

CREATE TABLE sequence (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  xzero_id INTEGER NOT NULL,
  sequence_size INTEGER NOT NULL,
  density INTEGER NOT NULL,
  FOREIGN KEY (xzero_id) REFERENCES xzero (id)
);
