DROP TABLE IF EXISTS xzero;
DROP TABLE IF EXISTS position;

CREATE TABLE xzero (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  formula TEXT UNIQUE NOT NULL,
  sequence_size INTEGER NOT NULL
);

CREATE TABLE position (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  p1 INTEGER NOT NULL,
  engine TEXT NOT NULL,
  p2_range INTEGER NOT NULL,
  p3_range INTEGER NOT NULL
);